### ISSUE TITLE
Scroll for multiple div?

### ISSUE THREAD

**Issue by 1ucay** [mrgnou/mouse-scroll-smoothing#2]
Hi, nice work! It would be possible add support for multiple div at same time? I mean div with overflow: scroll;

Thank you.

**Comment by leo-cheron** [comment]
Hey, this approach is based on global window scroll event and can't work in a DOM element scope.

**Comment by 1ucay** [comment]
It is possible some workaround?

**Comment by leo-cheron** [comment]
Not with that approach.
